### ISSUE TITLE
I can't install lightonml package

### ISSUE THREAD

**Issue by laiou** [lightonai/transfer-learning-opu#2]
After git clone this repo and creating and activating virtualenv environment,i'm use "pip install <path_to_repo>"to install this repo.But there is an error is"requests.exceptions.HTTPError:404 client Error : Not Found for url : https://pypi.org/simple/lightonml".

**Comment by iacolippo** [comment]
Hi @laiou, thanks for your interest. 

The `lightonml` and `lightonopu` packages are not publicly available yet. Currently, you can only install them from [LightOn Cloud servers](https://cloud.lighton.ai/). Note that you can remove these packages from the dependencies and run all the scripts that don't require a GPU, but you need a server with an OPU in order to run scripts using `lightonml` and `lightonopu`.

**Comment by TheBojda** [comment]
@iacolippo I think it would help a lot if you would release an open-source OPU simulator. If people could try the samples simply, and they would see it is working (on low speed because of the emulation) then they would rather try the real OPU, or pay for it.

**Comment by iacolippo** [comment]
Hi @TheBojda , you are right. We are working on releasing publicly `lightonml` on PyPi, with the capability of simulating the OPU. You can expect this by the end of the month 🙂

**Comment by CharlesB2** [comment]
Hi, `lightonml` is now pip installable, and is available on Github at https://github.com/lightonai/lightonml
